### ISSUE TITLE
College Education Framework

### ISSUE THREAD

**Issue by amsos** [Govrn-HQ/foundation#5]
# College Education Framework

## Description
We want to create a movement model/value framework and playbook that could act as a starter template for College Clubs looking to either become a DAO or start a DAO.  The output would be:
- A Movement Model template that others can fork
- Opinionated playbook on the DAO to create (i.e. Moloch, Token, Aragon) 
- Cultural norms and processes

## Why this is important/beneficial for the Govrn Community
Not only do we think that college groups are a great use case for DAOs, but also we want to ensure that the next generation of leaders/workers are familiar with DAOs as DAOs look to become a new way for people to create new communities. 

## Proposal Link + Additional Resources
- [This is a first version](https://github.com/amsos/Movement-Proposals/blob/demo/communities/templates/CollegeClub_Starter.csv) that Ross and myself created
- Will have David add notes from the first meeting below

**Comment by amsos** [comment]
Next steps to move this along:
- [ ] Determine key milestones, deliverables, and timelines.
- [ ] Determine projected initiative budget
- [ ] Decide on the distribution mechanism for initiative budget (i.e. Movement Model + staking)

Goal is to have this agreed to by **Friday 1/14**

**Comment by botchedway** [comment]
Meeting Notes 01/11/22 
(stream of consciousness, excuse the lack of structure) 

-  governance for Bridge USA 
- proof of engagement -> movement model 
- singular contribution an contribute to multiple frameworks (notes +5, sourcecred  +3)
- movement model very customizable -> tooling starter template 
- forkable framework 
- building bottom-up management 
- can integrate with anything 
- POAP excellent example of primitive ( can just see POAP attendance) 
- social, academic, etc... (forkable framework)
- Whatsapp integration 

- Bot (Kevin Malone) 
- /join command 
- edit in post 
- /report 
- can propose contributions
- airtable 
- define easiest way to contribute 
- bot DMs 
- pulls directly from Github 
- Airtable can manage completely 
- approval screen -> generates Github file -> approved & rejected 

- Govrn is an open platform 
- mnemonic filter 
- setting up two parts -> creating the **template** & **playbook**
- DIY
- Github makes everything ownable by user 

- start from template of ground up 
- education/learning club framework 
- Github -> bot -> feedback loop
- Notion snapshot-> activity -> member breakdown
- MGD (Github) ->Discord opens up roles 

- 3 milestones ( template, 5 DAO's, time launch ) 
- ^ compensated w Govrn budget -> can convert points to shares in Govrn DAO 

GOALS BY FRIDAY (1/14) 
- [x] Milestones
- [x] Budget

**Comment by botchedway** [comment]
Proposed Initial Milestones: 

1. Handbook for utilizing without web 3 jargon (still onboarding in a tangible way)
2. Forkable template defining what "governance" looks like (limits, constraints, and actionable items) 
3. Defined modes of interaction and input (how does a community actually plug in and contribute, identify learning curves, and areas of weakness) 

Proposed Initial Budget: 

- [ ] Would have to shoot that back to larger group (fiat or crypto? reference budgets and projects? compensating collective or individuals?)

**Comment by amsos** [comment]
Nice - i like this direction, want do you think about these modifications:

## Milestones:
1. Handbook for utilizing without web 3 jargon (still onboarding in a tangible way) | [Delivered in a HackMD or Google Sheet]
2. Forkable template with required documents and folder (Activity Tabs, Best Practices) | [Delivered via a PR to Govrn Repo]
3. Community Handbook:  Defined modes of interaction and input (how does a community actually plug in and contribute, identify learning curves, and areas of weakness) | [Delivered in a HackMD or Google Sheet]
4. Test usage with 3 DAOs | [Delivered by having 3 DAOs using the above deliverables, Govrn can help provide users for this]

## Budget:
- Bounty: 5k 
- Bonus: A bonus of 2k for completion within 4 weeks.

## Work Attribution:
- Weighted Blended Average between Movement Model and Retro Evaluation
- Details:  Set up a movement model specific to this initiative to track initial contributions + do a retro at end of the project where the team self-evaluates the contributions. 
- We will combine the points you earn from both the movement model and evaluation, then use the following weighting (75% movement model, 25% retro) to come up with each persons' total points.
- The percentage of points you have then correlates to the percent of budget you receive.

**Comment by amsos** [comment]
Nice - i like this direction, want do you think about these modifications:

## Milestones:
- Handbook for utilizing without web 3 jargon (still onboarding in a tangible way) | [Delivered in a HackMD or Google Sheet]
- Forkable template with required documents and folder (Activity Tabs, Best Practices) | [Delivered via a PR to Govrn Repo]
- Community Handbook: Defined modes of interaction and input (how does a community actually plug in and contribute, identify learning curves, and areas of weakness) | [Delivered in a HackMD or Google Sheet]
- Test usage with 3 DAOs | [Delivered by having 3 DAOs using the above deliverables, Govrn can help provide users for this]


## Budget:
- Bounty: 3k
- Bonus: A bonus of 1k for completion within 4 weeks.

## Work Attribution:
- Weighted Blended Average between Movement Model and Retro Evaluation
- Details: Set up a movement model specific to this initiative to track initial contributions + do a retro at end of the project where the team self-evaluates the contributions.
- We will combine the points you earn from both the movement model and evaluation, then use the following weighting (75% movement model, 25% retro) to come up with each persons' total points.
- The percentage of points you have then correlates to the percent of budget you receive.

**Comment by botchedway** [comment]
[Gitbook] as a mode of delivery
